export const educationLevels = {
  en: [
    { value: '', label: 'All Education' },
    { value: 'CLASS_1_5', label: 'Class 1-5' },
    { value: 'CLASS_6_8', label: 'Class 6-8' },
    { value: 'CLASS_9_10', label: 'Class 9-10' },
    { value: 'CLASS_11_12', label: 'Class 11-12' },
    { value: 'DIPLOMA', label: 'Diploma / ITI' },
    { value: 'GRADUATE', label: 'Graduate (BA/BSc/BCom)' },
    { value: 'BTECH', label: 'B.Tech / Engineering' },
    { value: 'MEDICAL', label: 'Medical / Nursing' },
    { value: 'CA', label: 'CA / CS / ICWA' },
    { value: 'MBA', label: 'MBA / PGDM' },
    { value: 'PHD', label: 'PhD / Doctorate' },
    { value: 'NONE', label: 'No Education Required' },
  ],
  hi: [
    { value: '', label: 'सभी शिक्षा' },
    { value: 'CLASS_1_5', label: 'कक्षा 1-5' },
    { value: 'CLASS_6_8', label: 'कक्षा 6-8' },
    { value: 'CLASS_9_10', label: 'कक्षा 9-10' },
    { value: 'CLASS_11_12', label: 'कक्षा 11-12' },
    { value: 'DIPLOMA', label: 'डिप्लोमा / ITI' },
    { value: 'GRADUATE', label: 'स्नातक (BA/BSc/BCom)' },
    { value: 'BTECH', label: 'बी.टेक / इंजीनियरिंग' },
    { value: 'MEDICAL', label: 'मेडिकल / नर्सिंग' },
    { value: 'CA', label: 'CA / CS / ICWA' },
    { value: 'MBA', label: 'MBA / PGDM' },
    { value: 'PHD', label: 'PhD / डॉक्टरेट' },
    { value: 'NONE', label: 'शिक्षा आवश्यक नहीं' },
  ],
  mr: [
    { value: '', label: 'सर्व शिक्षण' },
    { value: 'CLASS_1_5', label: 'इयत्ता 1-5' },
    { value: 'CLASS_6_8', label: 'इयत्ता 6-8' },
    { value: 'CLASS_9_10', label: 'इयत्ता 9-10' },
    { value: 'CLASS_11_12', label: 'इयत्ता 11-12' },
    { value: 'DIPLOMA', label: 'डिप्लोमा / ITI' },
    { value: 'GRADUATE', label: 'पदवीधर (BA/BSc/BCom)' },
    { value: 'BTECH', label: 'बी.टेक / अभियांत्रिकी' },
    { value: 'MEDICAL', label: 'वैद्यकीय / नर्सिंग' },
    { value: 'CA', label: 'CA / CS / ICWA' },
    { value: 'MBA', label: 'MBA / PGDM' },
    { value: 'PHD', label: 'PhD / डॉक्टरेट' },
    { value: 'NONE', label: 'शिक्षण आवश्यक नाही' },
  ]
};
